// 一覧表示
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';

export default function Homes() {
  const [lists, setLists] = useState([]);

  useEffect(() => {
    fetch('http://localhost:3001/api/diaries')
      .then(res => res.json())
      .then(data => setLists(data))
      .catch(err => console.error('データ取得エラー:', err));
  }, []);
console.log(lists)
  return (
    <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>日記一覧</h1>
      <Link href={'/DiaryForm'}><button>新規作成</button></Link>
      <ul>
        {lists.map((post) => (
          <li key={post.id}>
              <div>
                <p>{post.title}-{post.date}</p>
                <Link href={`/lists/${post.id}`}><button>詳細</button></Link>
              </div>
          </li>
        ))}
      </ul>
    </>
  );

}
