// 一覧表示
import Head from 'next/head';
import Link from 'next/link';

export async function getStaticProps() {
  // ダミーのブログデータを取得（実際にはAPIやデータベースから取得）
  const lists = [
    {id:1 ,title:"今日の記憶" , exp:"内容1"},
    {id:2 ,title:"今日の思い出" , exp:"内容2"}
  ]

  return {
    props: {
      lists,
    },
  };
}

export default function DiaryList({ lists }) {
  return (
    <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>ブログ一覧</h1>
      <ul>
        {lists.map((post) => (
          <li key={post.id}>
              <div>
                <h2>{post.title}</h2>
                <p>{post.exp}</p>
                <Link href={`/lists/${post.id}`}><button>詳細</button></Link>
              </div>
          </li>
        ))}
      </ul>
    </>
  );
}